#version: "3.8"
services:
  cost_db:
    image: mysql:5.7
    container_name: cost_free_db
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes: # 挂载
      - ./conf/mysql:/etc/mysql/conf.d
      - ./data/mysql/:/var/lib/mysql
      - ./logs/mysql/:/var/log/mysql
      - ./conf/init.d:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
    privileged: true 
    networks:
      - cost_free

  cost_redis:
    image: redis:latest
    container_name: cost_free_redis
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes: # 挂载
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime
    restart: always
    privileged: true 
    networks:
      - cost_free


  costapp:
    image: cc2c/app-env:v1.0
    container_name: cost_free_app
    ports:
      - 8080:8080
    volumes: # 挂载上传文件
      - ./data/uploads/:/usr/local/wuyusoft/uploads/
      - ./logs/server/:/usr/local/wuyusoft/logs/
      - ./conf/app/:/usr/local/wuyusoft/app/
      - /etc/localtime:/etc/localtime
    depends_on:
      - cost_db
      - cost_redis
    restart: always
    privileged: true
    command: ["/usr/local/wuyusoft/app/wait-for-it.sh", "cost_free_db:3306", "--", "/usr/local/wuyusoft/app/start.sh"]
    networks:
      - cost_free

  cost_nginx:
    image: nginx:latest
    container_name: cost_free_nginx
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - ./conf/html5:/usr/share/nginx/html5
      - ./conf/web:/usr/share/nginx/html
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
    restart: always
    privileged: true 
    depends_on:
      - costapp
    networks:
      - cost_free
      

      
networks:
  cost_free:
    driver: bridge
